# This module is crucial.
# Cheers taken from http://www.sd40.bc.ca/kelvin/compliments.htm

import random


CHEERS = [
    "Great!",
    "Phenomenal!",
    "Superb!",
    "Cool!",
    "Out Of Sight!",
    "Excellent!",
    "Unbelievable Work!",
    "Two Thumbs Up!",
    "You've Got It!",
    "Way To Go!",
    "Terrific!",
    "Outstanding Performance!",
    "You've Outdone Yourself!",
    "Marvelous!",
    "Amazing Effort!",
    "Bravo!",
    "Exceptional!",
    "Breathtaking!",
    "Wonderful!",
    "You're Special!",
    "Keep Up The Good Work!",
    "First Rate Work!",
    "Fantastic Work!",
    "You Should Be Proud!",
    "I Knew You Had It In You!",
    "Very Good!",
    "Stupendous!",
    "Sensational!",
    "A+ Work!",
    "Awesome!",
    "You're A Great Example For Others!",
    "You Made It Happen!",
    "You're A Real Trooper!",
    "It Couldn't Be Better!",
    "You're A Good Sport!",
    "You Made The Difference!",
    "Take A Bow!",
    "Super Job!",
    "You're Unique!",
    "It's Everything I Hoped For!",
    "How Thoughtful Of You!",
    "Nice Going!",
    "You're A Class Act!",
    "Well Done!",
    "You're Inspiring!",
    "How Artistic!",
    "You Go The Extra Mile!",
    "Hooray For You!",
    "Great Answer!",
    "You Deserve A Hug!",
    "High Five!",
    "Extra Special Work!",
    "Wow!",
    "You're Getting Better!",
    "You're Tops!",
    "You're Amazing!",
    "What A Great Idea!",
    "You Figured It Out!",
    "You've Got What It Takes!",
    "You're Neat!",
    "You're A Joy!",
    "You're A Shining Star!",
    "Spectacular Work!",
    "You're #1!",
    "The Time You Put In Really Shows!",
    "Remarkable!",
    "How Extraordinary!",
    "You're A Winner!",
    "You Came Through!",
    "That's Incredible!",
    "5 Star Work!",
    "You're Super!",
    "You Can Do It!",
    "You're The Greatest!",
    "Sweet!",
    "Great Effort!",
    "How Original!",
    "What A Genius!",
    "You're A Natural!",
    "Very Brave!",
    "You're A Pleasure To Know!",
    "Way To Go!",
    "You're Sharp!",
    "Congratulations!",
    "I'm Proud Of You!",
    "Thank You For Caring!",
    "I'm Impressed!",
    "You're Very Talented!",
    "You're A Champ!",
    "Right On!",
    "You're A-OK!",
    "Magnificent!",
    "You've Earned My Respect!",
    "You've Made Progress!",
    "Outstanding Effort!",
    "Neat Work!",
    "I Love It!",
    "Beautiful!",
    "Clever!",
    "Brilliant!",
    "That's Perfect!",
    "Right On!",
    "Expressive!",
    "You've Improved!",
    "Keep It Up!",
    "Nice One!",
    "Wicked!",
    "Incomparable!",
    "Incredible!",
    "Great Job!",
    "Stunning!",
    "You Rule!",
    "You Rock!",
    "That's The Way!",
    "Good For You!",
    "A Job Well Done!",
    "Way To Use Your Head!",
    "Radical!",
    "Alright!",
    "Wonderful!",
    "Getting Better All The Time!",
    "Worthy Of An Oscar!",
    "Better Than Ever!",
    "Super Duper!",
    "Great Dedication!",
    "Top Notch!",
    "Hats Off To You!",
    "Spectacular!",
    "Very Courageous!",
    "I Like It!",
    "Great Enthusiasm!",
    "Lovely!",
    "Very Resourceful!",
    "It's A Masterpiece!",
    "Yes!"
]


def random_cheer():
    return random.choice(CHEERS)
